// src/routes/Header.svelte
<script lang="ts">
	import { IsMobile } from "$lib/components/hook/is-mobile.svelte.js";

	import * as Avatar from "$lib/components/ui/avatar/index.js";
	import { Button } from "$lib/components/ui/button/index.js";
	import { Separator } from "$lib/components/ui/separator/index.js";
	import { ModeToggle } from "$lib/components/ui/mode-toggle/index.js";

	import { Github, Linkedin, Mail, Menu, X } from "@lucide/svelte";

	import Profile from "$lib/assets/images/profile.webp";

	const isMobile = new IsMobile();
	let isOpened = $state(false);
</script>

<header class="bg-background sticky top-0 z-50 shadow-md">
	<div class="flex h-16 items-center justify-between px-4">
		<div class="flex h-full items-center gap-4">
			<Avatar.Root class="size-8 rounded-none">
				<Avatar.Image src={Profile} alt="Profile picture" />
				<Avatar.Fallback class="rounded-none">RH</Avatar.Fallback>
			</Avatar.Root>
			<h1 class="text-xl font-bold">Romain HURÉ</h1>
		</div>

		{#if isMobile.current}
			<div class="flex h-full items-center gap-4">
				<Button
					variant="outline"
					size="icon"
					onclick={() => (isOpened = !isOpened)}
					aria-label="Menu"
				>
					<Menu class="!size-6" />
				</Button>
			</div>

			<div
				class={`bg-background fixed inset-0 z-50 transition-opacity duration-300 ${
					isOpened ? "opacity-100" : "pointer-events-none opacity-0"
				}`}
			>
				<div class="flex h-full flex-col items-center justify-center">
					<Button variant="link">
						<a
							href="https://github.com/Neo-Diamons"
							target="_blank"
							aria-label="GitHub"
							rel="noopener noreferrer"
							class="flex items-center gap-2"
						>
							<Github /> GitHub
						</a>
					</Button>
					<Button variant="link">
						<a
							href="https://www.linkedin.com/in/romain-hur%C3%A9/"
							target="_blank"
							aria-label="LinkedIn"
							rel="noopener noreferrer"
							class="flex items-center gap-2"
						>
							<Linkedin /> LinkedIn
						</a>
					</Button>
					<Button variant="link">
						<a
							href="mailto:romain.hure@epitech.eu"
							aria-label="Email"
							class="flex items-center gap-2"
						>
							<Mail /> Email
						</a>
					</Button>
					<ModeToggle>Theme</ModeToggle>
					<Button variant="link" onclick={() => (isOpened = false)}>
						<X /> Close
					</Button>
				</div>
			</div>
		{:else}
			<div class="flex h-full items-center gap-4">
				<a
					href="https://github.com/Neo-Diamons"
					target="_blank"
					aria-label="GitHub"
					rel="noopener noreferrer"
				>
					<Github class="h-6 w-6" />
				</a>
				<a
					href="https://www.linkedin.com/in/romain-hur%C3%A9/"
					target="_blank"
					aria-label="LinkedIn"
					rel="noopener noreferrer"
				>
					<Linkedin class="h-6 w-6" />
				</a>
				<a href="mailto:romain.hure@epitech.eu" aria-label="Email">
					<Mail class="h-6 w-6" />
				</a>
				<ModeToggle />
			</div>
		{/if}
	</div>
	<Separator />
</header>

// src/components/Layout/Header.tsx
import { useState } from "react";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/avatar.tsx";
import { Github, Linkedin, Mail, Menu, X } from "lucide-react";
import { ModeToggle } from "./mode-toggle.tsx";
import { Button } from "@/components/ui/button.tsx";
import { Separator } from "@/components/ui/separator.tsx";
import { useIsMobile } from "@/hooks/use-mobile.tsx";
// @deno-types="@/vite-env.d.ts"
import Profile from "@/assets/profile-little.webp";

function HeaderDesktop() {
  return (
    <div className="flex justify-between gap-4 px-4 h-16">
      <div className="flex items-center h-full gap-4">
        <Avatar className="rounded-none h-8 w-8">
          <AvatarImage src={Profile} alt="Profile picture" />
          <AvatarFallback className="rounded-none">RH</AvatarFallback>
        </Avatar>
        <h1 className="text-xl font-bold">Romain HURÉ</h1>
      </div>
      <div className="flex items-center h-full gap-4">
        <a
          href="https://github.com/Neo-Diamons"
          target="_blank"
          aria-label="GitHub"
          rel="noopener noreferrer"
        >
          <Github className="h-6 w-6" />
        </a>
        <a
          href="https://www.linkedin.com/in/romain-hur%C3%A9/"
          target="_blank"
          aria-label="LinkedIn"
          rel="noopener noreferrer"
        >
          <Linkedin className="h-6 w-6" />
        </a>
        <a href="mailto:romain.hure@epitech.eu" aria-label="Email">
          <Mail className="h-6 w-6" />
        </a>
        <ModeToggle />
      </div>
    </div>
  );
}

function HeaderMobile() {
  const [isOpened, setIsOpened] = useState(false);

  return (
    <div className="flex justify-between items-center px-4 h-16">
      <div className="flex items-center h-full gap-4">
        <Avatar className="rounded-none h-8 w-8">
          <AvatarImage src={Profile} alt="Profile picture" />
          <AvatarFallback className="rounded-none">RH</AvatarFallback>
        </Avatar>
        <h1 className="text-xl font-bold">Romain HURÉ</h1>
      </div>
      <div className="flex items-center h-full gap-4">
        <Button variant="icon" onClick={() => setIsOpened(!isOpened)}>
          <Menu className="!h-6 !w-6" />
        </Button>
      </div>

      <div
        className={`fixed inset-0 z-50 bg-background transition-opacity duration-300 ${
          isOpened ? "opacity-100" : "opacity-0 pointer-events-none"
        }`}
      >
        <div className="flex flex-col items-center justify-center h-full">
          <Button asChild variant="link">
            <a
              href="https://github.com/Neo-Diamons"
              target="_blank"
              aria-label="GitHub"
              rel="noopener noreferrer"
              className="flex items-center gap-2"
            >
              <Github /> GitHub
            </a>
          </Button>
          <Button asChild variant="link">
            <a
              href="https://www.linkedin.com/in/romain-hur%C3%A9/"
              target="_blank"
              aria-label="LinkedIn"
              rel="noopener noreferrer"
              className="flex items-center gap-2"
            >
              <Linkedin /> LinkedIn
            </a>
          </Button>
          <Button asChild variant="link">
            <a
              href="mailto:romain.hure@epitech.eu"
              aria-label="Email"
              className="flex items-center gap-2"
            >
              <Mail /> Email
            </a>
          </Button>
          <ModeToggle>Theme</ModeToggle>
          <Button variant="link" onClick={() => setIsOpened(false)}>
            <X /> Close
          </Button>
        </div>
      </div>
    </div>
  );
}

export default function Header() {
  const isMobile = useIsMobile();

  return (
    <header className="sticky top-0 z-50 bg-background shadow-md">
      {isMobile ? <HeaderMobile /> : <HeaderDesktop />}
      <Separator />
    </header>
  )
}
